#!/bin/sh
a=$#;
for i in $* ; do
	if [ -f $i ]; then
		if [ -x $i -a -r $i ]; then
			echo $i ">>skaitomas/vykdomas";
		elif [ -x $i -a ! -r $i ]; then
			echo $i ">>neskaitomas/vykdomas";
		elif [ ! -x $i -a -r $i ]; then
			echo $i ">>skaitomas/nevykdomas";
		elif [ ! -x $i -a ! -r $i ]; then
			echo $i ">>neskaitomas/nevykdomas";
		fi;
	fi;
done;