#!/bin/sh
read a;
b=0;
while [ $b -ne 1 ]
do
	#echo $a;
	if [ "$a" = "pirmadienis" ]; then
		echo "Monday";
	elif [ "$a" = "antradienis" ]; then
		echo "Tuesday";
	elif [ "$a" = "treciadienis" ]; then
		echo "Wednesday";
	elif [ "$a" = "ketvirtadienis" ]; then
		echo "Thursday";
	elif [ "$a" = "penktadienis" ]; then
		echo "Friday";
	elif [ "$a" = "sestadienis" ]; then
		echo "Saturday";
	elif [ "$a" = "sekmadienis" ]; then
		echo "Sunday";
	elif [ "$a" = "q" ]; then
		exit 0;
	elif [ "$a" = "Q" ]; then
		exit 0;
	elif [ $a -eq 1 ]; then
		echo "Monday";
	elif [ $a -eq 2 ]; then
		echo "Tuesday";
	elif [ $a -eq 3 ]; then
		echo "Wednesday";
	elif [ $a -eq 4 ]; then
		echo "Thursday";
	elif [ $a -eq 5 ]; then
		echo "Friday";
	elif [ $a -eq 6 ]; then
		echo "Saturday";
	elif [ $a -eq 7 ]; then
		echo "Sunday";
	else
		echo "Reikia irasyti skaiciu 1-7 arba diena pirmadienis - sekmadienis. Q - iseiti.";
	fi;
	read c;
	a=$c;
done;